### ISSUE TITLE
Número de colaboradores

### ISSUE THREAD

**Issue by lauramcastro** [galu8/ValidacionAutomatica#2]
Aínda que parece que fixo alomenos os dous últimos commit, un dos catro membros do equipo non aparece como colaborador, o usuario do commit non se identifica correctamente como un dos colaboradores do repositorio.

**Comment by manoelfolgueira** [comment]
Resolto. Facía as operacións ao repositorio remoto con un email diferente ao que teño en GitHub.

**Comment by lauramcastro** [comment]
@manoelfolgueira Ok, se o problema está identificado e resolto, podedes pechar o issue sen problemas. Ou re-abríchelo por outra razón?
