### ISSUE TITLE
Posible problema de eficiencia al obtener la duración de la emisora

### ISSUE THREAD

**Issue by adrianleira** [galu8/ValidacionAutomatica#7]
Sería interesante añadir un atributo Duración a la clase ContenidoAbstracto. Esto evitaría llamar a este método cada vez que se modifica la lista de contenidos y con ello aumentar la eficiencia al refrescar el valor de la duración total de la emisora.

Por esto mismo puede que sea más rentable añadir en el método agregar o eliminar una instrucción que modifique este valor Duración y no hacer una llamada recorriendo toda la lista de objetos para calcular su valor total.

**Comment by diegolamas** [comment]
En un principio pensamos en hacerlo como comentas, pero, como nosotros permitimos añadir emisoras dentro de emisoras, nos dimos cuenta de lo siguiente:
Tienemos dos emisoras: emisora1 y emisora2.
Si agregamos emisora2 dentro de emisora1 y después agregamos una canción a la emisora interna (emisora2), ¿cómo actualizamos el atributo duración de la emisora externa (emisora1)? Nuestro método para obtener la duración lo que hace es recorrer recursivamente el contenido de la emisora.

**Comment by lauramcastro** [comment]
Podéis cerrar este issue si habéis decidido no variar vuestra implementación.

Espero ver el escenario que menciona @diegolamas en las pruebas de ambos equipos ;-).
